[package]
name = "threaded-capture"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.image]
version = "0.23.14"
default-features = false

[dependencies.nokhwa]
path = "../.."
default-features = false
features = ["output-threaded"]

[target.'cfg(target_os = "macos")'.dependencies.nokhwa]
path = "../.."
default-features = false
features = ["output-threaded", "input-avfoundation"]

[target.'cfg(target_os = "windows")'.dependencies.nokhwa]
path = "../.."
default-features = false
features = ["output-threaded", "input-msmf"]

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies.nokhwa]
path = "../.."
default-features = false
features = ["output-threaded", "input-native"]